---
name: Template para Pull Requests
about: Estructura base para la creación de un Pull Request
title: ''
labels: ''
assignees: dvegaa20
---

# [ Nombre de Pull Request ]

## Descripción

Descripción detallada de los cambios realizados en este PR.

## Issue Relacionado

#<número_del_issue>

## Tipo de Cambio

- [ ] Corrección de errores (bug fix)
- [ ] Nueva característica (feature)
- [ ] Mejora de rendimiento (performance improvement)
- [ ] Otro (especificar)

## Capturas de Pantalla (si es aplicable)

Adjunta capturas de pantalla que muestren visualmente los cambios realizados, si es aplicable.

